version: '3.8'
services:
  db:
    # image: mysql:5.7.12 # failed with errors when i was reworking migrations
    image: mysql:5.7
    platform: linux/x86_64
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=leadgogo
      - MYSQL_PASSWORD=leadgogo
      - MYSQL_DATABASE=leadgogo
    ports:
      - '8777:3306'
